### ISSUE TITLE
Towny Support

### ISSUE THREAD

**Issue by Devillion** [Spazzinq/FlightControl#1]
Can you add towny support for only flying within your town claims?

**Comment by Spazzinq** [comment]
Which Towny plugin would that be? (Link please!)

**Comment by LlmDl** [comment]
@Spazzinq He's probably talking about Towny, go ahead and use w/e you'd like from my plugin TownyFlight ( https://github.com/TownyAdvanced/TownyFlight ) if you'd like to also support Towny.

**Comment by Spazzinq** [comment]
Is "Towny" just one plugin? I thought there were many different implementations of it, hmmph. I'll take a look tomorrow 👍 

Thanks for the offer, I'll also look at that tomorrow.

**Comment by LlmDl** [comment]
Towny has largely not had the fractured development that has been seen with Factions. It has a history going back to the hMod days before Bukkit and has had 3-4 lead developers so far.

**Comment by LlmDl** [comment]
Take a look at TownyFlight to see which events you probably want to hook anyways.

**Comment by Spazzinq** [comment]
Sorry for the lengthy wait--I will be releasing a BETA version to test hopefully this weekend after I finish automatic configuration updates and some other requested features. Thanks for using FlightControl!

**Comment by Spazzinq** [comment]
Feel free to test the new beta containing Towny support & much more of my sweat n' tears
https://github.com/Spazzinq/FlightControl/releases/tag/2.7-Beta

Let me know how it works out 👍

**Comment by Spazzinq** [comment]
Closed due to inactivity

**Comment by Spazzinq** [comment]
(also because it was added)
