### ISSUE TITLE
FabledSkyblock Support

### ISSUE THREAD

**Issue by HamezGH** [Spazzinq/FlightControl#105]
**Describe the feature**
In FabledSkyblock players can unlock "island flight" as an island upgrade. It would be great if this was supported by this plugin. So the player can have access to fly if they have it unlocked on their island.
...

**Describe possible alternative solutions**
All players can fly when on or visiting an island that has the flight upgrade unlocked.
...

**Additional context**
https://docs.songoda.com/fabled-series/fabledskyblock
...

**Comment by Spazzinq** [comment]
Added in DEV version
