### ISSUE TITLE
Random warn in console

### ISSUE THREAD

**Issue by LuluxClient** [Spazzinq/FlightControl#107]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
Lulux#4614

**Describe the bug** *(if not just an error)*
 Getting a random error in console

**Error** *(if there's an error, use gist to paste it)*
 Getting this random warn in my console : https://pastebin.com/TTRQC2rM

**Configuration** *(use gist to paste)*
 https://pastebin.com/4aqKLzsk

**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
No one was online

**Server Version** *(e.g. Spigot 1.8.8)*
1.8.8 Tacospigot

**Comment by Spazzinq** [comment]
Fixed by b9a5cb0
