### ISSUE TITLE
Lands Hook NPE on FlightControl v4.1.8-BETA

### ISSUE THREAD

**Issue by arturek1666** [Spazzinq/FlightControl#11]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
Player can't fly in own region(lands) and it's giving an error
 ...
 
**Error** *(if there's an error, use gist to paste it)*
https://gist.github.com/arturek1666/9f22156fb9b53a44c86f070cb21fcf66
(Same gist was used for error and config
 ...
 
**Configuration** *(use gist to paste)*
https://gist.github.com/arturek1666/9f22156fb9b53a44c86f070cb21fcf66
 ...
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
flightcontrol.ownland
 ...
 
**Server Version** *(e.g. Spigot 1.8.8)*
1.15.1
 ...

**Comment by Spazzinq** [comment]
Fixed in version 4.1.11-BETA. Download it [here](https://github.com/Spazzinq/FlightControl/suites/383988039/artifacts/943404) (no config changes).

**Comment by Spazzinq** [comment]
I don't know how it was caused, but what I did should fix it.
