### ISSUE TITLE
GriefDefender API Update

### ISSUE THREAD

**Issue by steven11304** [Spazzinq/FlightControl#115]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
Bread#4709

**Describe the bug** *(if not just an error)*

 
**Error** *(if there's an error, use gist to paste it)*
https://paste.gg/p/anonymous/37bbfa999a444161833969e83e397438
**Configuration** *(use gist to paste)*
https://paste.gg/p/anonymous/a4c3b44289f94db2a54373ae3e3d6afd
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
no
**Server Version** *(e.g. Spigot 1.8.8)*
1.16.5

**Comment by Spazzinq** [comment]
Waiting for version of GriefDefender to determine if replacement is necessary.

**Comment by steven11304** [comment]
[griefdefender-bukkit-2.0.0-DEV.zip](https://github.com/Spazzinq/FlightControl/files/6751093/griefdefender-bukkit-2.0.0-DEV.zip)

**Comment by steven11304** [comment]
> Waiting for version of GriefDefender to determine if replacement is necessary.

[griefdefender-bukkit-2.0.0-DEV.zip](https://github.com/Spazzinq/FlightControl/files/6751097/griefdefender-bukkit-2.0.0-DEV.zip)
