### ISSUE TITLE
Disable flight when coming near another player.

### ISSUE THREAD

**Issue by EvilSlime** [Spazzinq/FlightControl#12]
Disable flight when near a player, radius can be set in config. Ofc we need a bypass perm!

**Comment by Spazzinq** [comment]
Note to self: don't forget bypass perm!

**Comment by MaximeMichaud** [comment]
> Note to self: don't forget bypass perm!

Don't forget !! Little reminder

**Comment by Spazzinq** [comment]
Apologies for the long wait, school was extremely stressful. The permission will be flightcontrol.nearbypass.
