### ISSUE TITLE
I defined a fly speed in config.yml, but when a player goes to nether or end and back he gets the default speed 1.0

### ISSUE THREAD

**Issue by thiagogebrim13** [Spazzinq/FlightControl#122]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
Thiago Gebrim # 0001

**Describe the bug** *(if not just an error)*
I defined a fly speed in config.yml, but when a player goes to nether or end and back he gets the default speed 1.0
 
**Configuration** *(https://pastebin.com/bQVcewni)*
 
**Server Version** *(Purpur 1.17.1)*
 ...

**Comment by Spazzinq** [comment]
What is your version of FlightControl? Because in version 4.8.16-BETA I added a speed change override

**Comment by thiagogebrim13** [comment]
using this version:
![image](https://user-images.githubusercontent.com/75040244/129435053-0ec75444-d016-45b8-bf8e-026a33763e39.png)

**Comment by thiagogebrim13** [comment]
In the latest version it seems to have fixed this problem. CI #369
