### ISSUE TITLE
Daily TempFly

### ISSUE THREAD

**Issue by iRama7** [Spazzinq/FlightControl#124]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Rama#5145** *(so I can notify you if I need more information or if an issue is fixed)*
 ...

**It just doesn't work, it should give me 1 hour or 30 minutes of fly per day but it doesn't give it to me.**
 ...
 

 ...
 
**https://gist.github.com/iRama7/4034fbce3e5bde2a584644cadb8cc680
   https://gist.github.com/iRama7/42848b708df0a63e464f49d4be15f754**
 ...
 
**- flightcontrol.category.mvp
   - flightcontrol.tempfly.mvp**  **No OP**
 ...
 
**git-Paper-570 (MC: 1.16.5)** 
 ...

**Comment by Spazzinq** [comment]
Try the latest dev version!
