### ISSUE TITLE
Could not pass event PlayerMoveEvent to FlightControl v4.3.11

### ISSUE THREAD

**Issue by Ebubekir728** [Spazzinq/FlightControl#134]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
 Proomp#8294

**Describe the bug** *(if not just an error)*
Error spamming on console whenever one player hits another player
 
**Error** *(if there's an error, use gist to paste it)*
https://paste.helpch.at/isujogubug.pl
 
**Configuration** *(use gist to paste)*
https://paste.helpch.at/dinisureto.bash
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
No default permissions.
 
**Server Version** *(e.g. Spigot 1.8.8)*
1.8.8

**Comment by Spazzinq** [comment]
You must use the latest DEV version.
