### ISSUE TITLE
Lands Api change (Here we go again)

### ISSUE THREAD

**Issue by arturek1666** [Spazzinq/FlightControl#14]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 
Using  the 4.2.3 Beta
**Describe the bug** *(if not just an error)*
Outdated Api 
 ...
 
**Error** *(if there's an error, use gist to paste it)*
https://gist.github.com/arturek1666/9f8c27224f786bc0fad29a6f1f3ed86a
 ...
 
**Server Version** *(e.g. Spigot 1.8.8)*
PaperSpigot 1.15.2
 ...

**Comment by Spazzinq** [comment]
Fixed in faee42c. Here's the [download link](https://github.com/Spazzinq/FlightControl/suites/432695897/artifacts/1499901).
