### ISSUE TITLE
Actionbar messages doesn't work in 1.18 test builds

### ISSUE THREAD

**Issue by MasterDev16** [Spazzinq/FlightControl#143]
Master#5262

When enabling action bar in lang.yml console gets spammed with an error message whenever a player enters/leaves their claim, whenever an action bar message should appear it doesn't.
 
https://pastebin.com/0LmGqUFA
 
https://pastebin.com/UmGJpTWz
 
flightcontrol.category.nameofcategory
 
1.18.1-71

**Comment by Spazzinq** [comment]
Fixed in latest dev build
