### ISSUE TITLE
PvPManager integration

### ISSUE THREAD

**Issue by milkmoron** [Spazzinq/FlightControl#18]
PvPManager has its own way to disable flight in combat, but when I use flightcontrol it reenables flight while tagged.

**Comment by Spazzinq** [comment]
Hey, are you talking about [this PvPManager](https://www.spigotmc.org/resources/pvpmanager.10610/) ?

**Comment by Spazzinq** [comment]
@milkmoron

**Comment by Spazzinq** [comment]
Added in 8b52f0f (4.4.6-BETA). The release version will be coming soon.
