### ISSUE TITLE
Changing Primary Plugin Command

### ISSUE THREAD

**Issue by Cionnaa** [Spazzinq/FlightControl#190]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
 Cionna#5722

**Describe the bug** *(if not just an error)*
 Trying to change the command for flight
 
**Error** *(if there's an error, use gist to paste it)*
 I would like to disable the /fly command for this plugin and rename it 
 - I'd like to change it to /tfly and keep /fly for Essentials fly
 
**Configuration** *(use gist to paste)*
 This is what I have the config set as but the /fly command is still calling to this plugin

  `# Allows the /fly command to be changed to a different command name (e.g. /votefly)
  fly_command_name: "tfly"
  `
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 I have OP
 
**Server Version** *(e.g. Spigot 1.8.8)*
 Purpur 1.19.2
 FlightControl 4.9.21

**Comment by Spazzinq** [comment]
User reported that the issue was fixed after restarting server (dealing with reflection often necessitates server restart).
