### ISSUE TITLE
Update to Support PlotSquared V5

### ISSUE THREAD

**Issue by Webman97** [Spazzinq/FlightControl#21]
**Describe the feature**
Support PlotSquared V5 (https://www.spigotmc.org/resources/plotsquared-v5.77506/)

**Error** *(if there's an error, use gist to paste it)*
https://gist.github.com/Webman97/74909a57c3dec5b2bdef194333cf20ac

**Server Version** *(e.g. Spigot 1.8.8)*
 Spigot 1.15.2

**Comment by Spazzinq** [comment]
Added in bfd36b2 (4.4.5-BETA). The release version will be coming soon,
