### ISSUE TITLE
Flight Speed Bug

### ISSUE THREAD

**Issue by CaptainFalxon** [Spazzinq/FlightControl#24]
**Describe the bug** 
Flight speed (0.5) is reset when the player cached in the FlightPlayer object is no longer up-to-date.
 
**Error** 
No error
 
**Configuration** 
https://gist.github.com/CaptainFalxon/bd74b3c5e6505c237df3bab39e190926
 
**FlightControl Permissions** 
flightcontrol.flyall
 
**Server Version** 
Paper 1.15.2

**Comment by Spazzinq** [comment]
Please provide more data if you wish for me to reopen this issue.

Closed due to inactivity.
