### ISSUE TITLE
Lag Spike On Join

### ISSUE THREAD

**Issue by DecypherMC** [Spazzinq/FlightControl#245]
currently working on development of my server and whenever i join, the server freezes for about 5 seconds. the spark ends up going down to `java.net.inet6addressimpl.lookupallhostaddr()` and it's a child of a flightcontrol node

Jar: 1.19.2 paper fork
FlightControl: 4.9.21
Decypher#0001

**Comment by Spazzinq** [comment]
Thanks for reporting this! I will be working on a fix soon!

**Comment by DecypherMC** [comment]
Any update?

**Comment by Spazzinq** [comment]
I believe I fixed this a long time ago with the plugin update changes. Let me know if it's still a problem
