### ISSUE TITLE
Temp fly doesn't drop you after fly is up.

### ISSUE THREAD

**Issue by mrunningmasterc** [Spazzinq/FlightControl#261]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
runningmaster#4601

**Describe the bug** *(if not just an error)*
When players temp fly time runs out, they don't drop to the ground. Also if they don't have any temp fly then can still fly.
 
**Error** *(if there's an error, use gist to paste it)*
 ...
 
**Configuration** *(use gist to paste)*
https://pastebin.com/jM1XC1y3
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
No OP. Added the lp group default permission set flightcontrol.fly.hub
 
**Server Version** *(e.g. Spigot 1.8.8)*
git-Purpur-1933 (MC: 1.19.3)*

**Comment by Spazzinq** [comment]
Solved on Discord. Note for other admins: You cannot use global as a tempfly category, and you must use the tempfly permission in order to run the tempfly timer.
