### ISSUE TITLE
FlightControl error on load

### ISSUE THREAD

**Issue by Shiade** [Spazzinq/FlightControl#28]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
 Hi! I would like to report a problem I have. I recently added the FlightControl plugin to my server, the thing is that when starting the server the plugin does not load correctly, it is not enabled and I get this error:
 
**Error** *(if there's an error, use gist to paste it)*
 https://pastebin.com/DTdKx3a8
 
**Configuration** *(use gist to paste)*
 https://pastebin.com/NneTCkPg
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 ...
 
**Server Version** *(e.g. Spigot 1.8.8)*
 I use version 1.12.2

**Comment by Spazzinq** [comment]
@Shiade Looks like an issue with your `categories.yml`. Please send that in a pastebin,

**Comment by Shiade** [comment]
https://pastebin.com/pBEBGwpA

**Comment by Spazzinq** [comment]
@Shiade On line 22, you need to have the world name with a + followed by the region name.

So `WORLDNAME+REGIONNAME: true`

**Comment by Spazzinq** [comment]
Please let me know if it works!
