### ISSUE TITLE
Permission Already Registered Error (will be fixed ASAP)

### ISSUE THREAD

**Issue by BrettplayMC** [Spazzinq/FlightControl#3]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
 ...Getting some weird 'errors' on startup.
 
**Error** *(if there's an error, use hastebin or gist)*
 ...
 https://pastebin.com/3Ex0D5R7
**Configuration** *(hastebin or gist)*
 ...https://pastebin.com/raw/MWAVUJGS
 
**FlightControl Permissions** *(given to player)* **& OP Status**
 ...essentials.fly
 
**Server Version** *(e.g. Spigot 1.8.8)*
 ...FluxSpigot 1.8.8 (fork of Taco which is a fork of Paper which is a fork of Spigot, Flux does some stuff for Factions servers with cannons).

**Comment by Spazzinq** [comment]
I have fixed this issue already, but I'm currently on vacation. Stay tuned around August when I get back!

**Comment by BrettplayMC** [comment]
:/ rip.  Well as far as I know at least it doesn't cause any issues.

**Comment by Spazzinq** [comment]
Yup, the problem is that I loaded permissions just in case people used PlugMan to enable it, but when loaded normally FlightControl throws a few errors.

You're correct that it doesn't cause any issues.

**Comment by BrettplayMC** [comment]
Ok thanks.  I'll close this.

**Comment by Spazzinq** [comment]
I'm reopening this because other people are reporting the same issue.

**Comment by Spazzinq** [comment]
Code with the fix has been published!

Waiting for review of other features before release...

**Comment by Spazzinq** [comment]
Woohoo! It's out now.
