### ISSUE TITLE
HuskTowns hook not working properly

### ISSUE THREAD

**Issue by matipoirierg** [Spazzinq/FlightControl#311]
Can't fly in HuskTowns claim:
error: https://pastebin.com/uT69iJD2

**Comment by Spazzinq** [comment]
Should be fixed in 2257950, let me know if you have further issues

**Comment by Spazzinq** [comment]
Also, use the bug reporting format

**Comment by matipoirierg** [comment]
Hi! the update worked, but randomly some users still can't fly on their towns, I can't reproduce why some of them can an others can't, but there are some errors on console when they try to use /fly.

Errors: https://mclo.gs/x9pAcGa
Sv version: git-Pufferfish-35 (MC: 1.20.2)
HuskTowns version: 2.6.1-00b67e8

I'm sorry if I'm not following the bug format but I couldn't find it.

**Comment by matipoirierg** [comment]
UPDATE: HuskTowns just released a new update with a rework on the API (V3) and now a better documentation; https://william278.net/docs/husktowns/api
More info:
APIs are now published per-platform; husktowns-bukkit and husktowns-common can now be targeted.
Simply update your build scripts to target the net.william278.husktowns:husktowns-bukkit artifact
HuskTownsAPI is no longer an abstract class; you can now retrieve an instance of the base class with HuskTownsAPI.getInstance()
See docs for more
