### ISSUE TITLE
Flight doesn't disable when outside the region 

### ISSUE THREAD

**Issue by Talesu** [Spazzinq/FlightControl#335]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
 talesu

**Describe the bug** *(if not just an error)*
When using the plugin"Lands" a player has the ability to fly, which is the intention.
When leaving their land, and they fall down their fly counter still goes down even tho they can't fly and get TP'd back to the ground.

Is there a option to disable flight after the fall instead of teleporting since I couldn't find any.
 
**Error** *(if there's an error, use gist to paste it)*
 No error.
 
**Configuration** *(use gist to paste)*
https://gist.github.com/Talesu/1c24272b6f3d93d96855b2c9afca398a
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
- flightcontrol.fly
- flightcontrol.flycommand
- flightcontrol.tempfly
- flightcontrol.category.plant
- flightcontrol.category.tempfly
- flightcontrol.tempfly.plant

**Server Version** *(e.g. Spigot 1.8.8)*
Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

**Comment by Talesu** [comment]
Forgot to include, no OP.

**Comment by Spazzinq** [comment]
Talesu, it sounds like your anticheat is teleporting them to the ground. FlightControl does not ever change the player position.
