### ISSUE TITLE
Grief Prevention Trusted Checks - Poor Performance

### ISSUE THREAD

**Issue by IllusionTheDev** [Spazzinq/FlightControl#379]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Discord Tag** *(so I can notify you if I need more information or if an issue is fixed)*
 @illusion_dev
 
**Describe the bug** *(if not just an error)*
 When checking the GriefPreventionTrustedCheck, GriefPrevention ends up building an error message which requires fetching the owner's name. This is a heavy operation (caused by a poor implementation).
 
 Suggested fix: Find an alternate method, or write your own allowBuild method that returns a boolean.
 
**Error** *(if there's an error, use gist to paste it)*
 N/A
 
**Configuration** *(use gist to paste)*
 N/A
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 N/A
 
**Server Version** *(e.g. Spigot 1.8.8)*
 N/A

**Comment by IllusionTheDev** [comment]
![image](https://github.com/Spazzinq/FlightControl/assets/28360622/902f4a63-8b2d-4ac8-862d-fae2976921cc)

**Comment by Spazzinq** [comment]
Thanks for reporting. I fixed it in 3eb0fce by 91442b9 by using ClaimPermission.Manage instead. Please follow the instructions in the Discord to download the latest dev version.
