### ISSUE TITLE
On Startup Error

### ISSUE THREAD

**Issue by xxJinxedxx** [Spazzinq/FlightControl#4]
**Describe the bug** *(if not just an error)*
On startup, some permission errors are spamming in to the console.
 
**Error** *(if there's an error, use hastebin or gist)*
 - https://hasteb.in/budokere.makefile
 
**Configuration** *(hastebin or gist)*
It's the generic one.
 
**FlightControl Permissions** *(given to player)* **& OP Status**
Haven't touched any.
 
**Server Version** *(e.g. Spigot 1.8.8)* 
PaperSpigot 1.8.8-R0.1-SNAPSHOT

P.S. - Thanks for the free plugin mate & for taking chunk of your time to make it.
Cheers.

**Comment by Spazzinq** [comment]
Reported and addressed in #3
