### ISSUE TITLE
MassiveFactions Hook NPE

### ISSUE THREAD

**Issue by 9budddy** [Spazzinq/FlightControl#43]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *(if not just an error)*
 ...Error on Startup
 
**Error** *(if there's an error, use gist to paste it)*
 ...https://pastebin.com/3wQdBw69
 
**Configuration** *(use gist to paste)*
 ...Factions Hook = true.
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 ...Server
 
**Server Version** *(e.g. Spigot 1.8.8)*
 ...1.8.8

**Comment by Spazzinq** [comment]
What version of MassiveFactions do you have?

**Comment by 9budddy** [comment]
This is my fault. We have a custom version/fork of MassiveCore which only causes issues when trying to grab different things from it. Apologies. It connects to regular MassiveCore Factions.

**Comment by Spazzinq** [comment]
Thank you for updating me on the issue!
