### ISSUE TITLE
Plugin Disabling on server  startup.

### ISSUE THREAD

**Issue by xxJinxedxx** [Spazzinq/FlightControl#5]
**Describe the bug** *(if not just an error)*
 Plugin will not enable on server startup.
 
**Error** *(if there's an error, use hastebin or gist)*
 - https://hasteb.in/ciqoheyo.swift
 
**Configuration** *(gist)*
 Deleted the old files to create new config.
 
**Server Version** *(e.g. Spigot 1.8.8)*
Paper Spigot 1.8.8-R0.1-SNAPSHOT

**Comment by Spazzinq** [comment]
Let me look into your problem!

It has to do with the bStats (plugin metrics) implementation,

**Comment by Spazzinq** [comment]
Looks like I posted the incorrect build of FlightControl. One moment please...

**Comment by Spazzinq** [comment]
Issue should now be resolved. Re-download the same 3.3 version from Spigot.
