### ISSUE TITLE
Permission for the /fly command

### ISSUE THREAD

**Issue by Bouwermax** [Spazzinq/FlightControl#54]
**Describe the feature**
Permission for the fly function so that you could use a common permission group whare you put the category in that you made, so you can block non-donators for flying in a specific area.

this is kinda for a specific use case. in my situation is that I have a group vs another group. The lands ar defined by WG, the reason I am requesting this feature is that when you give the category permission to a group there is no other check that you can use like a /fly permission node. 

What I like to see is a permission node for the /fly command this function could be toggled so existing setups won't run in any comparability problems.

**Comment by Spazzinq** [comment]
Self-note: config option necessary so an update doesn't change the functionality to existing servers
