### ISSUE TITLE
SuperiorSkyblock2 Support

### ISSUE THREAD

**Issue by MinecraftAdmin** [Spazzinq/FlightControl#62]
**Describe the feature**
Would appreciate support for Islands and Member Island for SuperiorSkyblock2

https://wiki.bg-software.com/#/superiorskyblock/api/

https://www.spigotmc.org/resources/%E2%9A%A1%EF%B8%8F-25-sale-superiorskyblock2-%E2%9A%A1%EF%B8%8F-the-best-core-on-market-%E2%9A%A1%EF%B8%8F-1-16-support.63905/

**Comment by Spazzinq** [comment]
Thank you for providing the API! I will add support as soon as possible, thank you.

**Comment by Spazzinq** [comment]
Download the latest dev version to try it out! If you need help, contact me on Discord (the download link is also located there).
