### ISSUE TITLE
NPE SpectatorModeCheck

### ISSUE THREAD

**Issue by iTaeyeonKim** [Spazzinq/FlightControl#63]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 
 4.7.13-BETA

**Describe the bug** *(if not just an error)*
No evidence
 
**Error** *(if there's an error, use gist to paste it)*
https://pastebin.com/pjMgBQCk

**Configuration** *(use gist to paste)*
https://gist.github.com/iTaeyeonKim/84735c87d06083456aaef0560387ee02
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
Yes, player have op.
 
**Server Version** *(e.g. Spigot 1.8.8)*
http://www.pics.rs/i/KKco2

**Comment by Spazzinq** [comment]
Cause: Player logs out before SpectatorModeCheck method can run.

Fixed in `4.7.18-BETA`.
