### ISSUE TITLE
NoSuchFieldError: CLOUD particle (v4.3.11)

### ISSUE THREAD

**Issue by kimzys** [Spazzinq/FlightControl#65]
***ALWAYS HAVE THE LATEST VERSION OF THE PLUGIN*** 

**Describe the bug** *Error occurred while enabling FlightControl v4.3.11*
 ...
 
**Error** *https://gist.github.com/kimzys/117adc56d08c92af81feda3dd1d468ec*
 ...
 
 
**Server Version** *paper.jar:SSSpigot-1.16.3-20201020-cf39e0d*
 ...

**Comment by Spazzinq** [comment]
Thank you for the report! I'm leaving myself some personal notes:

- NoSuchFieldError: CLOUD particle
- Incorrect particle class (ParticleManager8)

**Could you try using the beta version available [here](https://github.com/Spazzinq/FlightControl/releases/tag/4.7.13-BETA)?**

**Comment by Spazzinq** [comment]
This issue is invalid as 1.16 users need to use the BETA version available on the Discord.
