### ISSUE TITLE
Faction land error message on enter. (Faction relations check)

### ISSUE THREAD

**Issue by xxJinxedxx** [Spazzinq/FlightControl#7]
**Describe the bug** 
 Error when 2 players are in the same faction territory. It seems that it doesn't matter if they are same factions or not.
P.S. - When disabling the fly feature in the factions plugin the error seems that it stops, and works fine.
 
**Error** https://paste.md-5.net/yuyilujoro.pl
 
**FlightControl Permissions** *(given to player)* **& OP Status** *(does the player have OP?)*
 perm - flightcontrol.factions.<CATEGORY>
 
**Server Version** *(e.g. Spigot 1.8.8)*
 Paper Spigot - 1.8.8-R0.1-SNAPSHOT
 FactionsUUID - v1.6.9.5-U0.5.0-b191
 FlightControl - 3.5

**Comment by xxJinxedxx** [comment]
Update:
Disabling the fly feature doesn't fix the error spam.

**Comment by Spazzinq** [comment]
Updated on Discord.

**Comment by Spazzinq** [comment]
Issue resolved on recompile.
