### ISSUE TITLE
Support GriefDefender

### ISSUE THREAD

**Issue by stonegray** [Spazzinq/FlightControl#72]
**Describe the feature**

Add support for toggling flight within [GriefDefender](https://www.spigotmc.org/resources/1-8-8-1-16-5-griefdefender.68900/) claims. GriefDefender is similar to GriefPrevention.

GriefDefender is a premium plugin, but licenced under MIT with source is available at https://github.com/bloodmc/GriefDefender

API: https://github.com/bloodmc/GriefDefenderAPI

**Comment by Spazzinq** [comment]
Hey @stonegray , the [latest dev version](https://github.com/Spazzinq/FlightControl/actions/runs/524343545) adds support for GriefDefender. Could you verify that it works correctly?

**Comment by Spazzinq** [comment]
Closed as no response was provided. The latest beta with support was officially released.
