### ISSUE TITLE
Faction support & command changer

### ISSUE THREAD

**Issue by LuluxClient** [Spazzinq/FlightControl#77]
**Describe the feature**
...

1st feature: Could you add a perm where the plugins ignores you since I want to use the faction fly feature from SaberFaction so I can have the temporary fly and the faction fly as 2 different things

2nd feature: Make it so you can change the /fly command (Flycommand: TempFly or t fly etc...)

**Describe possible alternative solutions** *(not required)*
...

None

**Additional context** *(not required)*
...

1st feature: Because if I do it the way I'm doing it now, both FlightControl and Saberfactions handle the fly at the same time for the same player

2nd feature: some people might want to change the fly command and it adds more customization to the plugin c:

**Comment by Spazzinq** [comment]
1. I will add a permission to ignore FlightControl status.
2. Why do you specifically want to change the command name? I'm trying to understand why it would be useful to your server.

**Comment by LuluxClient** [comment]
Its for design purposes for example if I want to have my fly called «
VoteFly » so people can do /vote fly so they know their is the votefly and
the permanent /fly

**Comment by Spazzinq** [comment]
Pourquoi tu n'utilises que FlightControl pour un mode de voler ? Est-ce qu'il y a des autres plugins que tu utilises pour gérer le vol ?

**Comment by LuluxClient** [comment]
> Pourquoi tu n'utilises que FlightControl pour un mode de voler ? Est-ce qu'il y a des autres plugins que tu utilises pour gérer le vol ?

Oui la faction fly de saberfaction, j'ai envie de créer 2 type de fly différent, un fly permanent pour un grade spécifique et un grade temporaire à chaque fois qu'un joueur vote par exemple (quand il vote ça exécute une commande) donc c'est pour ça que avoir la possibilité de changer la commande sera un truc cool par rapport à ce système
